# Settings
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 500
TICK_TIME_MS = 100
CAPTION = "Flappy Python"

GRAVITY = 8.0

BIRD_START_VELOCITY_Y = 0
BIRD_JUMP_VELOCITY_Y = -30
BIRD_MAX_VELOCITY = 50
BIRD_MAX_ANGLE = 45
BIRD_START_X = -30
BIRD_START_Y = SCREEN_HEIGHT / 2
BIRD_HEIGHT = 50
BIRD_IMAGE_FILE = 'resources/bird.bmp'

OBSTACLE_GAP_X = 0.8 * SCREEN_WIDTH
OBSTACLE_START_X = 1.2 * SCREEN_WIDTH
OBSTACLE_START_VELOCITY_X = -20
DOOR_HEIGHT_IN_BIRDS = 2.5
OBSTACLE_IMAGE_FILE = 'resources/pipe-vertical.bmp'
OBSTACLE_CAP_IMAGE_FILE = 'resources/pipe-cap.bmp'

TITLE_FONT = 'Helvetica,Arial'
TITLE_FONT_SIZE = 50
TITLE = 'Flappy Python'

SCORE_FONT = 'Helvetica,Arial'
SCORE_FONT_SIZE = 40
SCORE_X = 10
SCORE_Y = 10
